# Generated by Django 4.2.6 on 2024-09-30 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_reg', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=60)),
                ('ape_paterno', models.CharField(max_length=60)),
                ('ape_materno', models.CharField(blank=True, max_length=60, null=True)),
                ('es_nacional', models.CharField(max_length=1)),
                ('pais', models.CharField(max_length=45)),
                ('habla_espanol', models.CharField(max_length=1)),
                ('idioma_natural', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='EstadoCheckInOut',
            fields=[
                ('id_est_ch', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'estado_check_in_out',
            },
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_estado', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_h', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('piso', models.DecimalField(decimal_places=0, max_digits=3)),
                ('numero', models.DecimalField(decimal_places=0, max_digits=3)),
                ('cant_personas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('habitaciones', models.DecimalField(decimal_places=0, max_digits=2)),
                ('banos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('metros', models.DecimalField(decimal_places=0, max_digits=3)),
                ('wifi', models.CharField(max_length=1)),
                ('tv_cable', models.CharField(max_length=1)),
                ('desayuno', models.CharField(max_length=1)),
                ('precio_noche', models.DecimalField(decimal_places=0, max_digits=6)),
                ('descripcion', models.CharField(max_length=300)),
                ('activa', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'habitacion',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_th', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'db_table': 'tipo_habitacion',
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id_tp', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_personal',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=45)),
                ('fecha_creacion', models.DateTimeField()),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('dias', models.DecimalField(decimal_places=0, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=7)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('qr', models.CharField(max_length=120)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='web.estadoreserva')),
                ('id_h', models.ForeignKey(db_column='id_h', on_delete=django.db.models.deletion.DO_NOTHING, to='web.habitacion')),
                ('id_reg', models.ForeignKey(db_column='id_reg', on_delete=django.db.models.deletion.DO_NOTHING, to='web.cliente')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_p', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('run', models.DecimalField(decimal_places=0, max_digits=8)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('nombre', models.CharField(max_length=60)),
                ('ape_paterno', models.CharField(max_length=60)),
                ('ape_materno', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=45)),
                ('activo', models.CharField(max_length=1)),
                ('id_tp', models.ForeignKey(db_column='id_tp', on_delete=django.db.models.deletion.DO_NOTHING, to='web.tipopersonal')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False)),
                ('anticipo_30', models.DecimalField(decimal_places=0, max_digits=6)),
                ('es_pagado', models.CharField(max_length=1)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='web.reserva')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_th',
            field=models.ForeignKey(db_column='id_th', on_delete=django.db.models.deletion.DO_NOTHING, to='web.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_g', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
                ('foto', models.ImageField(upload_to='galeria')),
                ('id_h', models.ForeignKey(db_column='id_h', on_delete=django.db.models.deletion.DO_NOTHING, to='web.habitacion')),
            ],
            options={
                'db_table': 'galeria',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('preg1', models.CharField(max_length=60)),
                ('resp1', models.CharField(max_length=60)),
                ('preg2', models.CharField(max_length=60)),
                ('resp2', models.CharField(max_length=60)),
                ('preg3', models.CharField(max_length=60)),
                ('resp3', models.CharField(max_length=60)),
                ('preg4', models.CharField(max_length=60)),
                ('resp4', models.CharField(max_length=60)),
                ('comentarios', models.CharField(max_length=60)),
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='web.reserva')),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_user',
            field=models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='web.usuarios'),
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id_cio', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('check_in_fh', models.DateTimeField()),
                ('check_out_fh', models.DateTimeField()),
                ('id_est_ch', models.ForeignKey(db_column='id_est_ch', on_delete=django.db.models.deletion.DO_NOTHING, to='web.estadocheckinout')),
                ('id_p', models.ForeignKey(db_column='id_p', on_delete=django.db.models.deletion.DO_NOTHING, to='web.personal')),
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='web.reserva')),
            ],
            options={
                'db_table': 'check_in_out',
            },
        ),
    ]
