# Generated by Django 4.2.6 on 2024-09-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_checkinout_id_cio_alter_encuesta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_user',
            field=models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='web.usuarios'),
        ),
    ]
