# Generated by Django 4.2.6 on 2024-09-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_cliente_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='num_star',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=1),
        ),
    ]
