# Generated by Django 4.2.6 on 2024-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_habitacion_num_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(default='fotos/no_disponible.jpg', upload_to='fotos'),
        ),
    ]
