# Generated by Django 4.2.6 on 2024-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_habitacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
