# Generated by Django 4.2.6 on 2024-09-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_habitacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('nombre', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=120)),
                ('comentario', models.CharField(max_length=220)),
                ('id_h', models.ForeignKey(db_column='id_h', on_delete=django.db.models.deletion.DO_NOTHING, to='web.habitacion')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
    ]
