# Generated by Django 5.1.1 on 2024-10-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_reserva_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cant_personas',
            field=models.IntegerField(default=1),
        ),
    ]
