# Generated by Django 5.1.1 on 2024-10-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_reserva_cant_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='emial',
            field=models.CharField(default='h@h.com', max_length=100),
        ),
    ]
