# Generated by Django 5.1.1 on 2024-10-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_cliente_emial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emial',
            new_name='email',
        ),
    ]
